version: '3.8'
services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
  nats:
    image: nats
    ports:
      - '4222:4222'
  redis:
    image: redis:7.2.5
    ports:
      - '6379:6379'
